language: julia

os:
  - linux
  - osx

julia:
  - nightly
  - 1.0
  - 0.7
  
after_success:
  - julia -e 'using Pkg; import Psycho; cd(joinpath(dirname(pathof(Psycho)), "..", paths...)); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; import Psycho; Pkg.add("Documenter"); cd(joinpath(dirname(pathof(Psycho)), "..", paths...)); include(joinpath("docs", "make.jl"))'