language: julia

os:
  - linux
  - osx

julia:
  - nightly
  - 1.0
  - 0.7
  
after_success:
  - julia -e 'cd(Pkg.dir("Psycho")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';