language: julia

os:
  - linux
  - osx

julia:
  - nightly
  - 1.0
  - 0.7
  
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Psycho")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'